spring:
  datasource:
    url: jdbc:mysql://localhost:3306/ddd_leave?serverTimezone=GMT%2B8&characterEncoding=UTF-8&useSSL=false&rewriteBatchedStatements=true
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        temp:
          use_jdbc_metadata_defaults: false
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL57Dialect
